### ISSUE TITLE
Fix back button behaviour

### ISSUE THREAD

**Issue by JamesLouie** [shenjiayi/technossus#7]
Currently there are many instances where the back button isn't doing what it should intuitively.

Ex: When we navigate from Live feed -> Project1.  But I want to get back to the live feed, so I click the back button.  What happens is that I am sent back to the login screen, which does me no good.

The only example of it seem to be working properly is when I am on the client page, and I click a client, I am taken to that specific client.  Hitting back takes me back to the client page.

I have a feeling this has to do with the activity stack, and our usage of different fragments as part of the activity, but it still being the 'same activity'.

This is sort of important, as the back button is a huge part of android navigation, but we can probably get around it during presentations if we can't figure out the issue.

**Comment by shenjiayi** [comment]
I have been looking into this problem. And feel it is hard to do. 
I found out that some explanation is that if we use tabs with fragments, it is safe to assume the user could switch/swipe a lot the tab fragments as he used the app.

**Comment by JamesLouie** [comment]
As it is the last week, if you think its too big of a issue, just focus on polishing up what we can.

**Comment by JamesLouie** [comment]
Sort of works, doesn't go back to login screen.  Not completely fixed, but for demo purposes good enough.

Commit 28e79541b2f757f3ac3d987edbd901969e7a3c7a
